# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
      - id: pretty-format-json
        args: ["--autofix", "--no-sort-keys"]
  - repo: https://github.com/smarterhq/shq_pre-commit_hooks
    rev: master
    hooks:
      - id: shellcheck
  - repo: https://github.com/prettier/prettier
    rev: 2.0.2
    hooks:
      - id: prettier
        args: ["--print-width=200", "--prose-wrap=preserve"]
