- id: shellcheck
  name: Shellcheck Bash Linter
  description: Performs linting on bash scripts
  entry: scripts/shellcheck.sh
  language: script
- id: terraform-fmt
  name: Terraform fmt
  description: Rewrites all Terraform configuration files to a canonical format.
  entry: scripts/terraform-fmt.sh
  language: script
  files: \.tf$
  exclude: \.+.terraform\/.*$
- id: circleci-config-validate
  name: CircleCI Config Validation
  entry: scripts/circleci-config-validate.sh
  language: script
  files: config.yml
  exclude: "^(?!.circleci/)"
- id: hadolint
  name: Hadolint Dockerfile Linter
  description: Dockerfile linter, validate inline bash, written in Haskell
  entry: scripts/hadolint.sh
  language: script
  files: (\.dockerfile|Dockerfile)$
- id: dockerfilelint
  name: Dockerfile Linter
  entry: dockerfilelint
  language: node
  additional_dependencies: [dockerfilelint]
  files: (\.dockerfile|Dockerfile)$
- id: prometheus-check-config
  stages: [commit]
  name: Check prometheus config files
  description: Check prometheus config files
  language: docker_image
  entry: --entrypoint /bin/promtool prom/prometheus:latest
  files: \.yml$
  args:
    - check
    - config
- id: prometheus-check-rules
  stages: [commit]
  name: Check prometheus rule files
  description: Check prometheus rule files
  language: docker_image
  entry: --entrypoint /bin/promtool prom/prometheus:latest
  files: \.yml$
  args:
    - check
    - rules
